# DefSec Security Testing Tool Configuration

# Scanning Settings
scan:
  max_threads: 50
  timeout: 1
  default_ports: "1-1000"

# Rate Limiting
rate_limit:
  requests_per_second: 10
  pause_between_scans: 2

# Vulnerability Database
vulndb:
  cache_duration: 3600  # in seconds
  max_results: 5

# Reporting
report:
  include_timestamps: true
  default_format: "json"
